# Generated by Django 3.0.7 on 2020-06-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200629_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='tag',
        ),
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
